name: WECommandBlock
version: ${project.version}
main: net.kunmc.lab.wecommandblock.WECommandBlock
api-version: 1.15
commands:
  weblock:
    description:
    usage: |
      /<command> run <filename> <WorldEditCommand>
      /<command> save <filename>
    permission: op
depend:
  - WorldEdit
